### PR TITLE
Separating Error and Success JS handling from init.html.twig for easier customization

### PR DESCRIPTION
**Pull request by IonBazan**

### CODE REVIEW

**Comment by Divi** [comment]
Great idea, thanks @janek2012

**Comment by IonBazan** [comment]
I also tought about creating a pre-submit action - it is great to hide any error messages before resubmitting form wit errors or do any other action. What do you think about this?

BTW, great Bundle!

**Comment by Divi** [comment]
It's a great idea, to implement validation for example.

:+1:

**Comment by IonBazan** [comment]
So brilliant today :8ball:

**Pull request merged**
